[package]
description = "Large fixed-size integers arithmetics"
homepage = "http://parity.io"
repository = "https://github.com/ethcore/bigint"
license = "MIT/Apache-2.0"
name = "bigint"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.2"

[dependencies]
rustc-hex = "1.0"
byteorder = "1.0"
heapsize = { version = "0.4", optional = true }
serde = { version = "1.0", optional = true }

[features]
heapsizeof = ["heapsize"]

[dev-dependencies]
serde_derive = "1.0"
toml = "0.4"
