[package]
name = "fixed-hash"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
heapsize = { version = "0.4", optional = true }
libc = { version = "0.2", default-features = false }
rand = { version = "0.3", optional = true }
rustc-hex = { version = "1.0", optional = true }

[features]
std = ["rustc-hex", "rand"]
heapsizeof = ["heapsize"]
